### ISSUE TITLE
Process.hrtime is undefined with Next.js since 0.0.5

### ISSUE THREAD

**Issue by snide** [LyraSearch/lyra#101]
**Describe the bug**

On upgrade to `0.1.1` (from `0.0.4`) the search function spits out a process error in Next.js

```
TypeError: process.hrtime is undefined
```

Guessing this might be due to the changes in  https://github.com/LyraSearch/lyra/commit/b51456c2c22b99337f492942697ad32299701f9b which were added to `0.0.5`

Here's a sandbox reproduction using the most popular TS/Next.js configuration

https://codesandbox.io/s/magical-carlos-3p11ow

Sorry I can't be more helpful and submit a PR, but I'm mostly a designer! Great little lib, ty for putting it together.

**Comment by micheleriva** [comment]
Thanks for reaching out, we're on it!
