### ISSUE TITLE
What is the best way to do date range search 

### ISSUE THREAD

**Issue by swftvsn** [LyraSearch/lyra#103]
I have documents with dates (Those can be converted to milliseconds since epoch values.) - what's the best way to formulate query like `where date is less than parameter` and text contains `Parrot`.

Is this something that is in the roadmap, or doable already?

**Comment by micheleriva** [comment]
Hi @swftvsn, as for now, we don't support query clauses. We have an open discussion in #36 about that, and we'll be releasing this feature in the short/mid term

**Comment by swftvsn** [comment]
Awesome @micheleriva! Thank you for the good work 🥇
