### ISSUE TITLE
JavaScript heap out of memory (node)

### ISSUE THREAD

**Issue by bacloud22** [LyraSearch/lyra#115]
I'm giving the node 6 gigs already,

I am trying to index a file of 6 million documents, but no worries; each document is literally like:

`{ title: "hello this is a Wikipedia title" }`

Most of titles are shorter actually, (wikipedia) titles dump. (the whole dump is 350 mb on disk, as text, so in memory I'm sure it is way lighter)

A second question please, I have already a tokenizer (`natural` library), so what I'm doing is:

```js
insert(index, {
    title:
        nex.join(' '),
});
```

So is there a way to deactivate Lyra tokenizer ? (and pass an array of words instead)

Thanks a lot

**Comment by micheleriva** [comment]
Hey @bacloud22 , how is that closed? Just curious

**Comment by bacloud22** [comment]
Hi @micheleriva ,
Sorry I didn't follow up. Simply I've run a tf-idf with so much sacrifice, as I dropped some edge words from documents. Edge words like ones very much repeating (prepositions, etc) and also very rare (nouns of cities etc)
Also I didn't test accuracy for now. It just fits my memory
