### ISSUE TITLE
Count term occurrencies in document

### ISSUE THREAD

**Issue by micheleriva** [LyraSearch/lyra#12]
**Is your feature request related to a problem? Please describe.**
Right now, we're not considering how many times a term appears in a document.

For instance, given the following strings:

* `"It's alive! It's alive!"`
* `"I saw them alive"`

When searching for `"alive"`, the first string should have priority as the term `"alive"` appears twice.

**Comment by mateonunez** [comment]
@micheleriva I have prepared a [branch](https://github.com/nearform/lyra/compare/main...mateonunez:lyra:feat/occurrences-sort) with working code for it. 

The `sort` options accepted are: `none` (as usual) and `relevance` (by occurrences). The "relevance" could be accepted as default if you want to implement a search by occurrences natively.

There are 2 methods: `getOccurrences(document, index, term)` that return the count of the occurrences in the document (uses a Regex for it). The other method is `sortResults(results, sort)` with a simple switch to manage all accepted sorting algorithms.

**Comment by micheleriva** [comment]
@mateonunez thanks! Any idea on how that affects performances?

**Comment by micheleriva** [comment]
Also, in which scenario would I want to sort the results by "random" order?

**Comment by mateonunez** [comment]
Initially, this implementation affects a lot of the performance of the search action.

Current timing:
```js
{
  elapsed: '114μs',
  hits: [
    {
      id: 'PmLDkPyPWlRPG5qFcmS_7',
      quote: "It's alive! It's alive!",
      author: 'H.P. Lovecraft'
    }
  ],
  count: 1
}
```

With occurrences implementation:
```js
{
  elapsed: '158μs',
  hits: [
    {
      id: 'qUMSJWBHvxJ0Islfwpfpz',
      quote: "It's alive! It's alive!",
      author: 'H.P. Lovecraft',
      occurrences: 2
    }
  ],
  count: 1
}
```

That implementation cost **~27.8% more** than the search time.

With the sort implementation:

```js
{
  elapsed: '162μs',
  hits: [
    {
      id: 'KGpFwdn5mbXgEpCRXamhd',
      quote: "It's alive! It's alive!",
      author: 'H.P. Lovecraft',
      occurrences: 2
    }
  ],
  count: 1
}
```

The first `occurrencesTime` cost about `40-50μs`. Then the cost it's about `0-3μs`:

```js
    {
      id: 'kdNXamfKo_CCFpTATPOvk',
      quote: 'I saw them alive. Alive man. You got it? Alive.',
      author: 'H.P. Lovecraft',
      occurrences: 3,
      occurrencesTime: '46μs'
    },
    {
      id: 'DQ0mXcVNSnv4hJ8Du34k8',
      quote: "It's alive! It's alive!",
      author: 'H.P. Lovecraft',
      occurrences: 2,
      occurrencesTime: '3μs'
    },
    {
      id: '_E5tQaXAXwuNmNFqSoCea',
      quote: 'I saw them alive. Alive man. You got it? Alive.',
      author: 'H.P. Lovecraft',
      occurrences: 3,
      occurrencesTime: '1μs'
    },
    {
      id: '7HqOPlGMRJtXXtKdh9eXp',
      quote: 'alive in the middle of the night.',
      author: 'H.P. Lovecraft',
      occurrences: 1,
      occurrencesTime: '1μs'
    },
    {
      id: 'JJ0Mec0ze_ivNFrZO4grh',
      quote: "Oh, I, oh I'm still alive",
      author: 'H.P. Lovecraft',
      occurrences: 1,
      occurrencesTime: '1μs'
    },
    {
      id: 'gSfPxZwmoY2tcu05aywoS',
      quote: 'I feel alive',
      author: 'H.P. Lovecraft',
      occurrences: 1,
      occurrencesTime: '0μs'
    },
    {
      id: 'NbYe5iNSLkJBwKNRj97ti',
      quote: 'Alive is the only thing I know',
      author: 'H.P. Lovecraft',
      occurrences: 1,
      occurrencesTime: '0μs'
    },
    {
      id: 'fXGKFc6oFdVMFk4OBc7Og',
      quote: 'Alive is the only thing I know',
      author: 'H.P. Lovecraft',
      occurrences: 1,
      occurrencesTime: '0μs'
    }
````

Regarding the `random` (or first in first out) order I was imagining to a situation where we need the data as we usually handle queues. So the first `document` inserted in the _database_ will be the first document selected in the search method.

**Comment by mateonunez** [comment]
I've tried it with **1M of documents**. The result is amazing! @micheleriva 

**Without implementation:**

```js
{
  elapsed: '421ms',
  hits: [
    {
      id: 'ZpRIoxvyzosuI6yNW47cx',
      quote: 'I saw them alive. Alive man. Did you get it? Alive.',
      author: 'H.P. Lovecraft'
    }
  ],
  count: 1000000
}
```

**With implementation:**

```js
{
  elapsed: '426ms',
  hits: [
    {
      id: '3PEwoThPgs0we8IBlxIoi',
      quote: 'I saw them alive. Alive man. Did you get it? Alive.',
      author: 'H.P. Lovecraft',
      occurrences: 3
    }
  ],
  count: 1000000
}
```

**Comment by micheleriva** [comment]
This is pretty rad. Would you mind opening a PR?

**Comment by mateonunez** [comment]
I could work on it, but there is just one question to understand: what should Lyra do in case the `limit` parameter is set? Should it compute all occurrences (and sort them) and then truncate the output? This operation could require more stress.

Currently, Lyra limits the results quitting from the cycle that retrieves the documents, then the occurrences are computed.
This means that: if I add 10 consecutive documents (increasing the occurrence by 1 each cycle) and then set the `limit` to 2, Lyra will only consider the first 2 documents (the first documents inserted).

**Simple Search with Relevance**

```js
{
  elapsed: '244μs',
  hits: [
    {
      id: 'DhQVMo6RI5IMpJyr8C5xf',
      quote: 'Repeat with me: alive, alive, alive',
      author: 'Oscar Wilde',
      occurrences: 3
    },
    {
      id: 'w6dIlijToS9GOaKEG6fBm',
      quote: 'Repeat with me: alive, alive',
      author: 'Oscar Wilde',
      occurrences: 2
    },
    {
      id: 'ME5jTyPK7slIZK9p0tu6u',
      quote: 'Repeat with me: alive',
      author: 'Oscar Wilde',
      occurrences: 1
    }
  ],
  count: 3
}
```

**Search with Relevance and Limit set to 1:**
```js
{
  elapsed: '22μs',
  hits: [
    {
      id: 'ME5jTyPK7slIZK9p0tu6u',
      quote: 'Repeat with me: alive',
      author: 'Oscar Wilde',
      occurrences: 1
    }
  ],
  count: 3
}
```

What do you think about it?

**Comment by mateonunez** [comment]
> Going "pseudo-logic":
> 
> 
> 
> ```diff
> 
>   private async _insert({ doc, id, language }: QueueDocParams): Promise<void> {
> 
>     const index = this.index;
> 
>     this.docs.set(id, doc);
> 
> 
> 
>     function recursiveTrieInsertion(doc: object) {
> 
>       for (const key in doc) {
> 
>         if (typeof (doc as any)[key] === "object") {
> 
>           throw ERRORS.UNSUPPORTED_NESTED_PROPERTIES();
> 
>           // @todo nested properties will be supported with the nexrt versions
> 
>           // recursiveTrieInsertion((doc as any)[key]);
> 
>         } else if (typeof (doc as any)[key] === "string") {
> 
>           const requestedTrie = index.get(key);
> 
>           const tokens = tokenize((doc as any)[key], language);
> 
> ++        const tokenFrequency = getTokenFrequency(tokens); // <-------- new function to count token frequency
> 
> 
> 
>           for (const token of tokens) {
> 
> --            requestedTrie?.insert(token, id);
> 
> ++            requestedTrie?.insert(token, [id, frequency]); // <------ just an idea, it doesn't have to be an array at all costs
> 
>           }
> 
>         }
> 
>       }
> 
>     }
> 
> 
> 
>     recursiveTrieInsertion(doc);
> 
>   }
> 
> ```
> 
> 
> 
> I would evolve around this idea to keep the time complexity as low as possible

Totally agree. I had thought that the best solution was to work directly on the composing Tries action.

I would like to play with your pseudo-logic and if the result is interesting I might do a PR, removing the "sort" in favour of #13.

**Comment by DanieleFedeli** [comment]
Cannot be implemented via sort of a score?
 
[tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) can be a good candidate.

**Comment by micheleriva** [comment]
@DanieleFedeli yes, `tf-idf` could be the way to go. When inserting a new document, we do that by creating a queue and indexing one doc at a time. That means that on very large documents, we could spend some more time analyzing the tokens using `tf-idf` or a similar technique (Jaccard index, etc.)

**Comment by micheleriva** [comment]
FYI I'm working on a prototype with `tf-idf`, let's see how it goes

**Comment by micheleriva** [comment]
FYI, the work is proceeding on https://github.com/nearform/lyra/pull/63
