### ISSUE TITLE
Error: Cannot find module '../stemmer/cjs/en'

### ISSUE THREAD

**Issue by mateonunez** [LyraSearch/lyra#126]
**Describe the bug**

The new release can't find module `'../stemmer/cjs/en'`, imported in `lyra.js:6`

**To Reproduce**
1. npm init --yes
2. npm install @lyrasearch/lyra@0.2.2
3. npm run start

**Expected behavior**

When Lyra is build, the stemmer path becomes wrong: it adds one level on the dist folder.

![image](https://user-images.githubusercontent.com/11861080/188730104-ec909da4-de43-4983-aa08-27c27f18bd08.png)

**esm stemmer import**
![image](https://user-images.githubusercontent.com/11861080/188730340-8e3b7647-134d-4e5d-be7f-479be3e082eb.png)

_the import should be: `import { stemmer } from "../../stemmer/cjs/en"`_

**cjs stemmer import**
![image](https://user-images.githubusercontent.com/11861080/188730400-cf9d65c6-fd19-42df-bab3-5b2d29a8a2e8.png)

_the import should be `const en_1 = require("../../stemmer/cjs/en");`_

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Node: v18.7.0
 - Lyra: v0.2.2

**Comment by AliMejbar** [comment]
Same Problem.
OS: macOS 13.0
Node: v18.7.0
Lyra: v0.2.2

**Comment by micheleriva** [comment]
Thanks for opening this, would you be available for opening a PR? 🙏
