### ISSUE TITLE
refactor: insert and insertWithHooks functions are almost identical

### ISSUE THREAD

**Issue by stearm** [LyraSearch/lyra#135]
Since the [insert](https://github.com/LyraSearch/lyra/blob/main/src/lyra.ts#L335) and the [insertWithHooks](https://github.com/LyraSearch/lyra/blob/main/src/lyra.ts#L370) are more or less the same functions, I'm wondering if it's worth adding a field inside the [InsertConfig](https://github.com/LyraSearch/lyra/blob/main/src/lyra.ts#L80) type like:

```ts
export type InsertConfig = {
  language: Language;
  enableAfterInsertHooks?: boolean;
};
```

and update the `insert` function like this:

```ts
export async function insert<S extends PropertiesSchema>(
  lyra: Lyra<S>,
  doc: ResolveSchema<S>,
  config?: InsertConfig,
): Promise<{ id: string }> {
  config = { language: lyra.defaultLanguage, ...config };
  const id = uniqueId();

  if (!SUPPORTED_LANGUAGES.includes(config.language)) {
    throw new Error(ERRORS.LANGUAGE_NOT_SUPPORTED(config.language));
  }

  if (!recursiveCheckDocSchema(doc, lyra.schema)) {
    throw new Error(ERRORS.INVALID_DOC_SCHEMA(lyra.schema, doc));
  }

  lyra.docs[id] = doc;
  recursiveTrieInsertion(lyra.index, lyra.nodes, doc, id, config, undefined, lyra.tokenizer as TokenizerConfigExec);
  trackInsertion(lyra);
  if (config?.enableAfterInsertHooks && lyra.hooks.afterInsert) {
    await hookRunner.call(lyra, lyra.hooks.afterInsert, id);
  }

  return { id };
}
```

Maybe it's too early to do this kind of refactoring but why not discuss it! 😄

**Comment by sundlemonflux** [comment]
Would be useful if hooks also got db instance itself for manipulation, just the document id is not overly useful as there isn't a way to access db inside the hook (as far as I know 😅 ).

**Comment by RafaelGSS** [comment]
That's expected. Hooks are still experimental, if we merge it into `insert` we would need to change its signature to return **always** a Promise, which is a breaking change.

We're evaluating a better approach and this likely will be refactored any time soon. By the way, would be great to see your use-cases using Hooks.

**Comment by micheleriva** [comment]
Closing this as Rafael's answer explains it 🙂
