### ISSUE TITLE
Can't search numbers or booleans

### ISSUE THREAD

**Issue by mateonunez** [LyraSearch/lyra#139]
**Describe the bug**
As defined in the type, is not possible to search terms different than `strings`.

![image](https://user-images.githubusercontent.com/11861080/192768058-2ff7066c-68cb-444d-a3a4-b56e855b65ea.png)

**To Reproduce**

```js
import {create, insert, search} from "@lyrasearch/lyra"

(() => {
  const lyra = create({
    schema: {
      author: "string",
      website: "string",
      contributors: "number",
      stars: "number",
      forks: "number",
      language: "string"
    }
  })

  insert(lyra, {
    author: "Lyra",
    website: "https://github.com/LyraSearch",
    contributors: 21,
    stars: 3350,
    forks: 62,
    language: "TypeScript"
  })

  const {hits} = search(lyra, { term: 62 })
})()
```

**Expected behavior**
Lyra's searches should support the types of the `PropertiesSchema` declared.

Anyway, whether I try to cast "**62**" _(forks property)_ into a string, the `hits` are empty.

```js
import {create, insert, search} from "@lyrasearch/lyra"

(() => {
  ...

  const {hits} = search(lyra, { term: "62" })
  console.log({hits}) // empty
})()
```

**Desktop (please complete the following information):**
 - Lyra `v0.2.4`
 - Node `v18.9.0`
 
UPDATED: **Additional context**
Playing with `node_modules` and the build of Lyra, changing the type of term is working fine:

**Boolean**
![image](https://user-images.githubusercontent.com/11861080/192773092-158ff1e8-9cd0-4525-995c-64f026991725.png)

**Number**
![image](https://user-images.githubusercontent.com/11861080/192773234-bad07f38-2b3c-4185-992a-4f8e0d18ae17.png)

**Comment by micheleriva** [comment]
Released in `v0.4.9`
