### ISSUE TITLE
Support list of strings as schema type

### ISSUE THREAD

**Issue by frankleng** [LyraSearch/lyra#155]
**Is your feature request related to a problem? Please describe.**
Would be useful to index list of strings/numbers as a schema type. 
ie.
```
const person = {
  name: 'John Doe',
  emails: ['john@gmail.com', 'frank@gmail.com']
}
```
**Describe the solution you'd like**
```
const index = create({
    schema: {
      name: "string",
      emails: "string[]",
      dates: "number[]",
```

**Describe alternatives you've considered**
we can do an `Array.join` on the string and search for partial match. but would like ability to perform exact match.

**Comment by micheleriva** [comment]
Hi @frankleng,
thank you for opening this!

I am just wondering what the search API would look like.

Given the following example:
```js
search(db, {
  term: 'quick brown fox',
  properties: ['myArrayProperty']
})
```

it means we should search through all the arrays that contain the terms `quick brown fox`, right? We can achieve the same result right now by creating the following instance:

```js
const db = create({
  schema: {
    myArrayProperty: 'string'
  }
})
```

and then insert data as follows:

```js
insert(db, {
  myArrayProperty: ['foo', 'bar', 'baz'].join()
})
```

During the tokenization process, Lyra will convert the `"foo,bar,baz"` string into three individual tokens, allowing you to obtain the exact same search experience as looking up an array.

Does that make sense to you?

**Comment by frankleng** [comment]
@micheleriva thanks. that makes sense. assuming it should be `myArrayProperty: ['foo', 'bar', 'baz'].join(',')`

re: API - how about
```
search(db, {
  term: ['quick', 'brown', 'fox'],
  op: 'and', // "or" as default, not necessary for v1
  properties: ['myArrayProperty']
})

**Comment by micheleriva** [comment]
So, we have plans for query clauses (#15), as for now Lyra only works in `AND` between tokens. We still need an agreement on the APIs, then it should be quite easy to implement it (we can just remove the intersection algorithm introduced with #150).

Please feel free to join the Slack channel if you want to be notified with every new release 🙂 https://join.slack.com/t/lyrasearch/shared_invite/zt-1gzvj0mmt-yJhJ6pnrSGuwqPmPx9uO5Q
