### ISSUE TITLE
Non-searchable types for Schema

### ISSUE THREAD

**Issue by shiba-sama** [LyraSearch/lyra#168]
I propose a non-searchable array type (similar to "stored" field in Elasticsearch).

- Currently the search database schema only permits a few primitives.
- A user may have a collection of objects to search over, some of which may be an array. For example an array of the `Bookmark` type below:
```typescript
type Bookmark = {
   title: string;
   url: string;
   tags: string[];
}
```
- There are some workarounds for this scenario, such as transforming tags to a string and then later splitting them back into an array when consuming the search results, or creating a separate Map with the desired data and storing a unique key in the search results.
- Permitting either a general non-searchable type or a more specific array type will reduce the data transformation necessary on every search.

**Comment by micheleriva** [comment]
Thank you @shiba-sama , that's a good point. I'll discuss an API proposal with @ShogunPanda and update you

**Comment by micheleriva** [comment]
Hi @shiba-sama,
I created an RFC for this issue: https://github.com/LyraSearch/lyra/issues/171

let me know what you think!

I'm going to close this to continue the conversation on #171
