### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by mateonunez** [LyraSearch/lyra#180]
**Describe the bug**
When searching for an inserted term, Lyra throws an error on the `lyraOccurrencies` variable.

**To Reproduce**
1. Initialize a new project with Lyra v.0.3.0
2. Create a new Lyra instance with a simple schema
3. Insert a document following Lyra's schema created
4. Search for a term

Or just paste this code

```js
const { create, insert, search } = require('@lyrasearch/lyra')

const db = create({ schema: { name: 'string', age: 'number' }})
insert(db, { name: 'john doe', age: 27 })
const results = search(db, { term: "john" })

console.log(results)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/11861080/201735232-2043f07f-1237-404a-b3b1-2b0a29aa1d5c.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Lyra v0.3.0
 - Node v18.12.1

**Comment by LBRDan** [comment]
Hey @mateonunez
This seems to me as related to the merge of #171 + #169
Maybe I changed something that was intended to trigger 100% of the time
Frequencies are not being added correctly, maybe due to something related to the skipped tests as commented [here](https://github.com/LyraSearch/lyra/pull/174#issuecomment-1313738180) (last phrase in the comment)

Could be this the reason @micheleriva ?

**Comment by mateonunez** [comment]
Going deepen the error seems to be generated by the non-string values defined in the schema.

This code works:

```js
const { create, insert, search } = require('@lyrasearch/lyra')

const db = create({ schema: { name: 'string', age: 'string' }})
insert(db, { name: 'john doe', age: '27' })
const results = search(db, { term: "john" })

console.log(results)
```

With the new release, we should define only searchable fields (**only strings**). This is strictly related to the semi-schemaless.

Should Lyra throw an error when a non-searchable field type is defined in the schema?

**Comment by micheleriva** [comment]
That's a bummer. We have a large number of unit tests that should have caught this issue specifically. Let me check and fix this ASAP

**Comment by micheleriva** [comment]
Oh got it. 100% my bad. Fixing now

**Comment by mateonunez** [comment]
Awesome! Thank you so much @micheleriva!
