### ISSUE TITLE
Create a CI process for testing Lyra on major browsers

### ISSUE THREAD

**Issue by micheleriva** [LyraSearch/lyra#189]
We need to create a CI process to test that Lyra continues working on web browsers by testing it through either Playwright or Cypress. This requires a simple web application + e2e tests in CI.

**Comment by rubiagatra** [comment]
Do you want to create directly HTML with this one and try to emulated searching with multiple browser?

```
<html>
  <body>
    <script type="module">
      import { create, search, insert } from "https://unpkg.com/@lyrasearch/lyra@latest/dist/esm/src/lyra.js";

      // ...
    </script>
  </body>
</html>
``` 

So we need
1. Simple web application (where we put it?)
2. Github Action that emulates multiple browsers?

is that correct @micheleriva ?
