### ISSUE TITLE
Facet Queries

### ISSUE THREAD

**Issue by sreenath-n** [LyraSearch/lyra#206]
Need support for Facet Queries like this:
https://typesense.org/docs/0.23.1/api/search.html#filter-results

![image](https://user-images.githubusercontent.com/69649218/206627064-4d03ba9c-5a2f-4b46-932f-7bd7490ed1cd.png)

**Comment by nicksav** [comment]
must have guys!

**Comment by micheleriva** [comment]
Thank you @sreenath-n for your feature request!
I do believe that this is something we need to support.

I'll update y'all as soon as we assign this a priority in our roadmap.

**Comment by micheleriva** [comment]
Hi @sreenath-n, @nicksav, facet queries is now a work in progress on #259 :)
