### ISSUE TITLE
26 seconds on a 200k rows index (just 387mb)

### ISSUE THREAD

**Issue by crivion** [LyraSearch/lyra#211]
**Describe the bug**
Searching on a disk persisted index of just 200k rows and a filesize of just 387mb takes 26 seconds.

**To Reproduce**
Create an index of 200k docs and persist it to the disk.

**Expected behavior**
Get results in under 0.20 seconds, up to 1 second I'd consider it reliable however anything over is simply unrealistic.

**Desktop (please complete the following information):**
 - OS: macOS (mbppro 15" apple cpu)
 - Browser: any
 - Version: lyra main 0.3.1 (0.0.4 for persistence)

Is this a normal behaviour, does it have any limitation in the number of records... etc?

**Comment by crivion** [comment]
Git won't let me upload the db dump as it's 300+ mb.
I can create the repo and send you an URL / or which way you prefer to download the DB dump?

<img width="1435" alt="Screenshot 2022-12-14 at 18 52 36" src="https://user-images.githubusercontent.com/15253384/207658200-061c36ac-8b3f-4ff4-abc7-382ff42936a3.png">

**Comment by crivion** [comment]
Nevermind, I managed with git lfs.

Here's the repo

https://github.com/crivion/lyrasearch-testing

Please let me know, it was exactly what the world needed!

**Comment by micheleriva** [comment]
Thank you so much, we'll investigate into this.

**Comment by crivion** [comment]
Wohoooo! 

I'm such a moron! 

Thanks a lot! 

I confirm everything's brilliant now - I'm very grateful for your enormous work!

**Comment by micheleriva** [comment]
@crivion no problem :)

**Comment by ShogunPanda** [comment]
@crivion We now want the real numbers tho. We're curious! :)

**Comment by crivion** [comment]
Averaging 0.05s on all requests which is impressive! Will deploy to production.

**Comment by micheleriva** [comment]
Awesome! Please share a production link (if public) 🙂
