### ISSUE TITLE
Lyra not ignoring tildes in words (Expected behavior?)

### ISSUE THREAD

**Issue by pimepan** [LyraSearch/lyra#213]
Hi! i am implementing lyra for our customers database that features around 8k entries and it works like a charm! Except for names that contain Tildes (eg: joaquín, josé). Our database is from spanish names

**Expected behavior**
I was hoping letters with tilde would index the same as letters without tilde. like ignoring them

**Additional context**
I am aware that at bit level, letters with tildes are different to tilde-less words. It would be nice to have to have a flag that be as "ignoreLetterHats" so you can index any letter with hats as its counterpart in the latin alphabet

**Comment by micheleriva** [comment]
Hi @pimepan,
Lyra should definitely remove tildes. Could you please help us reproduce the case? You can also reach out privately on Slack (https://join.slack.com/t/lyrasearch/shared_invite/zt-1gzvj0mmt-yJhJ6pnrSGuwqPmPx9uO5Q), we'd love to hear feedback from you!

**Comment by micheleriva** [comment]
Hi @pimepan,
@toomuchdesign has been able to replicate and he's working on it. We'll keep you posted

**Comment by toomuchdesign** [comment]
Lyra internal architecture is currently undergoing a relevant refactor, therefore we're going to review this issue after it. I've opened [this issue](https://github.com/LyraSearch/lyra/issues/230) to track my findings so far.

**Comment by micheleriva** [comment]
fixed by https://github.com/LyraSearch/lyra/pull/271
