### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null occurs during plugin-data-persistence import

### ISSUE THREAD

**Issue by Zombobot1** [LyraSearch/lyra#219]
**Describe the bug**
I'm trying to import a persistence function in browser (using vite dev): `import { exportInstance } from '@lyrasearch/plugin-data-persistence'`, and I get an error: `Uncaught TypeError: Class extends value undefined is not a constructor or null` with warning: `Module "stream" has been externalized for browser compatibility. Cannot access "stream.Transform" in client code.`

This is the [reason](https://github.com/vitejs/vite/issues/5963)

**To Reproduce**
1. Go to [sandbox](https://codesandbox.io/p/sandbox/stoic-snowflake-f6hj6y?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A6%7D%5D&file=%2Fsrc%2Fmain.tsx)
2. Click on 'open in new tab'
3. Press f12

**Expected behavior**
I don't think that this plugin is environment agnostic. Even though streams can be polyfilled I consider it to be an antipattern. Moreover, `persistToFile` doesn't have sense in browsers and I guess it is not intended to be called there.

**Comment by Zombobot1** [comment]
Duplicate of https://github.com/LyraSearch/plugin-data-persistence/issues/2

**Comment by isaachinman** [comment]
@Zombobot1 The data persistence repo now 404s. I am facing the exact same issue.
