### ISSUE TITLE
Allow custom id

### ISSUE THREAD

**Issue by Zombobot1** [LyraSearch/lyra#220]
**Is your feature request related to a problem? Please describe.**
To delete a document from lyra I need to save its id somewhere.

**Describe the solution you'd like**
Users can specify which field can be used as id during schema declaration.

**Describe alternatives you've considered**
Iterate over all `docs` to find matching data by its id and return doc's id for removal.

**Comment by micheleriva** [comment]
Hi @Zombobot1,
thank you for your feature request. I think it makes sense, but it would only work if the `id` property is defined in the schema definition.

Let's take the following examples:

```js
import { create } from '@lyrasearch/lyra'

const db = create({
  schema: {
    id: 'string',
    foo: 'string'
  }
})
```

in the above example, we could easily implement a feature to delete a document by `id` property.

We wouldn't be able to do the same for the following schema:

```js
const db = create({
  schema: {
   ___ id: 'string',
    foo: 'string'
  }
})
```

unless you specify which one is the ID field with a new API, for instance:

```js
const db = create({
  schema: {
   ___ id: 'string',
    foo: 'string'
  },
  id: '___id'
})
```

but this would cause inconsistent DX if a user is not interested in having a custom `id` field.

Therefore, I'd personally wait for query filters and clauses to create a unified way of deleting stuff depending on certain conditions (i.e.: `WHERE MyCustomID == '123123'`

what do you think?

**Comment by Zombobot1** [comment]
Yes, I wanted to declare a custom id field in my schema. You're right that some users might omit ids and in this case it is possible to auto generate them. [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#structuring_the_database) has such DX. I think omitting id is an edge case because usually people add fulltext search to a table / collection that is stored in a database. For search on a documentation / blog site id might be page's url. If I am right, lyra's current DX is focused on fulfilling an edge case scenario and can be improved.

Query filters are also a decent solution to my problem. However, I assume they will lead to additional indexing that could have been avoided.

**Comment by micheleriva** [comment]
>  If I am right, lyra's current DX is focused on fulfilling an edge case scenario and can be improved.

Yes, and we highly recommend using Lyra _the immutable way_ when on an edge network. Need to change the data? Just make a new deployment, do not mutate the database directly.

> Query filters are also a decent solution to my problem. However, I assume they will lead to additional indexing that could have been avoided.

It really depends on how we'll implement filters; I don't think we would need additional indexing tho. We will keep you posted on this one!

**Comment by micheleriva** [comment]
Another alternative: what if we create a hook that allows you to intercept document IDs creation? Something like:

```js
import { create } from '@lyrasearch/lyra'

create({
  schema: {
    name: 'string'
  },
  hooks: {
    // Totally made up hook name, just an example
    beforeCreateID: (document) => {
      return `${document.slug}-${document.id}` // just an example again
    }
  }
})
```

**Comment by Zombobot1** [comment]
My main problem is the size of the serialized index.

I want to talk a little bit about my use case. I'm building a notion-like knowledge management system hosted on the edge (cloudflare workers, r2, d1). In my system users have hundreds of independent search indexes, and some of them can grow up to 20 MB. Because users often change their pages, I need to update indexes every time.

```ts
function deleteFromLyra(d: typeof db, id: str) {
  for (const [docId, doc] of Object.entries(d.docs)) {
    if (doc?.id === id) remove(d, docId)
  }
}

// update index
const newPage = deriveNew(oldPage)
const paragraphs = newPage.split('\n')
deleteFromLyra(db, newPage.id)
insertBatch(db, paragraphs.map((p) => ({ id: newPage.id, text: p ))
uploadLyra(db)
saveLocalLyra(db)
```

This solution is not optimal because mobile users might have to download and upload big indexes.
I need to store `paragraph.id` inside a document in lyra and write my own synchronisation logic to avoid this problem. I'm afraid that `page.id` increases index size although it is not searchable and `paragraph.id` only worsens this problem. Should I use an unsearchable type in my schema to avoid that? 

With custom ids, I might try to use integers to get more compact `msgPack` serialization and simplify removal.
Maybe it is possible to implement an efficient index merge if custom ids are unique between several lyra indexes. In this case I can store isolated indexes per page and merge them on demand. However, I think I am the only one interested in such implementation.

I don't see how hooks can simplify my business logic, so I have nothing to say about them.

**Comment by ezzaouia** [comment]
If I may, this issue is, in part, related to https://github.com/LyraSearch/lyra/issues/112. 
@ShogunPanda suggested a solution to enable custom ids: https://github.com/LyraSearch/lyra/issues/112#issuecomment-1235440493

Quote:
> That said, @micheleriva, adding support to this is trivial since it will mostly (we just have to detect if already existing) to change this line https://github.com/LyraSearch/lyra/blob/main/src/lyra.ts#L337 to something like:
```
const id = config?.id ?? uniqueId();

if(lyra.docs[id]) {
   throw new Error(`A document with id "${id}" already exists.`);
}
```

**Comment by vassbence** [comment]
I have a somewhat similar use case where I deleting by ID would come in handy. I'm building a small serverless full-text search service with EFS and Lambda to have text search for items stored in DynamoDB.

Basically the source of truth is DynamoDB and I'm streaming data changes to Lyra, so when a document is added, updated or deleted from DynamoDB I'd like to do the exact same thing in Lyra so it's up to date.

Inserting is fine, but deleting and updating is not possible AFAIK due to not being able to delete by ID in Lyra. (Updating could be done with deleting and re-inserting the fresh document, so all I need is deleting by ID).

**Comment by ShogunPanda** [comment]
@Zombobot1 If I see it correctly, if we implement the fixed I suggested in #112 you should be good to go, isn't it?

**Comment by Zombobot1** [comment]
Yes

**Comment by micheleriva** [comment]
Hi @Zombobot1,
this will land in `v0.4.0`. I'm closing this in favor of #112, where we pursue the same goal.

Thanks again for opening this!
