### ISSUE TITLE
hit is always empty

### ISSUE THREAD

**Issue by abhay187** [LyraSearch/lyra#221]
**Describe the bug**
I have just started testing Lyra on a small project.

**To Reproduce**
Clone this repo to reproduce https://github.com/abhay187/lyra-test
[Codesandbox](https://codesandbox.io/p/github/abhay187/lyra-test/csb-0izmcd/draft/busy-cache?file=%2Fmain.js&workspace=%257B%2522activeFileId%2522%253A%2522clbv9j0xr00077ohdgaoffndh%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clbv9jkdz000f2e6991sxrqcj%2522%253A%257B%2522key%2522%253A%2522clbv9jkdz000f2e6991sxrqcj%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clbv9nqtz008f2e69mne9gpcm%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clbv9jkdz000f2e6991sxrqcj%2522%252C%2522spacesOrder%2522%253A%255B%2522clbv9jkdz000f2e6991sxrqcj%2522%255D%257D)

**Expected behavior**
The search should return a response

https://user-images.githubusercontent.com/61496865/208517982-0f2f6aa8-2f3f-4e66-8e17-9353436b95b8.mov

**Comment by mateonunez** [comment]
Hey @abhay187, thanks for opening this.

You can easily resolve that issue by passing an array of objects following your schema definition:

```js
const addData = async () => {
	const docs = [
		{ word: 'Indian Institute of Technology (BHU) Varanasi' },
		{ word: 'Indian Institute of Technology Bhilai' },
		{ word: 'Indian Institute Of Technology Bhubaneswar' },
		{ word: 'Indian Institute of Technology Bombay' },
		{ word: 'Indian Institute of Technology Delhi' },
		{ word: 'Indian Institute Of Technology Dharwad' },
		{ word: 'Indian Institute of Technology Guwahati' },
		{ word: 'Indian Institute of Technology Jodhpur' },
		{ word: 'Indian Institute of Technology Kanpur' },
		{ word: 'Indian Institute of Technology Kharagpur' }
	]

	await insertBatch(db, docs)
}
```

You can find more documentation here: https://docs.lyrasearch.io/usage/insert-data

**Comment by abhay187** [comment]
thanks @mateonunez It was really a silly mistake.  Sometimes a different eye can quickly identify a bug. Thanks again.
