### ISSUE TITLE
Cant search numbers when defaultLanguage is russian

### ISSUE THREAD

**Issue by lpite** [LyraSearch/lyra#226]
**Describe the bug**
Cant search numbers when defaultLanguage is russian

**To Reproduce**
1. `const db = create({
  schema: {
    num: "string",
    name: "string"
  },
  defaultLanguage:"russian"
});`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: 16.17

**Comment by mateonunez** [comment]
Hi @lpite, thanks for opening this!

Can you provide a reproduction of this issue? It would be helpful for anyone

**Comment by lpite** [comment]
@mateonunez added
