### ISSUE TITLE
Persisting database on cloudflare kv-store

### ISSUE THREAD

**Issue by abhay187** [LyraSearch/lyra#229]
**Describe the solution you'd like**
I think building Search DB every time is too much work for cases where data has not changed so if somehow I can store the database to kV-store in Cloudflare. It will be pretty easy and efficient to search, update and delete.

I tried storing DB as JSON.stringfy(instance) and retrieving it as JSON.parse(instance). 
Getting error:- Trace TypeError: lyra.tokenizer.tokenizerFn is not a function. Obviously, because we can't pass executable functions using JSON.

**Comment by mateonunez** [comment]
Hi @abhay187, Lyra Team has created an official plugin to store a Lyra instance: [plugin-data-persistence](https://github.com/LyraSearch/plugin-data-persistence). Have you tried it? If the error persists, can you provide a reproducible example of the error?

**Comment by abhay187** [comment]
Using the above plugin gave the following error - Module not found: Can't resolve 'fs'.
Others are also facing the same issue with plugin [Module not found: Can't resolve 'fs'](https://github.com/LyraSearch/plugin-data-persistence/issues/9)

**Comment by mateonunez** [comment]
> Obviously, because we can't pass executable functions using JSON.

This is the reason why you're getting that error. Lyra works as expected, so we have to follow the thread on the `plugin-data-persistence` repository.

I think the only solution is to use the official plugin, considering https://github.com/LyraSearch/plugin-data-persistence/issues/9 where we need "minimal reproduction" of the error.

**Comment by abhay187** [comment]
Give me 5 minutes.

**Comment by abhay187** [comment]
Hey, @mateonunez here we go https://github.com/abhay187/lyra-data-persistance-bug. Comment out the plugin import `import { persistToFile } from '@lyrasearch/plugin-data-persistence'` for the page to load. The search result will be printed in the console.

Getting below error while building.
<img width="1440" alt="Screenshot 2023-01-05 at 4 46 49 PM" src="https://user-images.githubusercontent.com/61496865/210769142-7ffb81a1-44e8-4fd1-a173-81b44daf638a.png">

**Comment by abhay187** [comment]
For further discussion follow this issue https://github.com/LyraSearch/plugin-data-persistence/issues/9
