### ISSUE TITLE
Documentation: wrong keyword

### ISSUE THREAD

**Issue by djibe** [LyraSearch/lyra#244]
Hello,

in the documentation page: <https://docs.lyrasearch.io/usage/insert-data#batch-insertion documentation>

you describe the `batchInsert` function.

In the example right below, you call the `insertBatch` function.

Is it `batchInsert()` or `insertBatch()` ?

Thanks

**Comment by micheleriva** [comment]
Nice catch, fixing it right now. Thanks! :)
