### ISSUE TITLE
README has broken link

### ISSUE THREAD

**Issue by djibe** [LyraSearch/lyra#247]
In the README we can read:

> See [builds](https://github.com/LyraSearch/lyra#builds) for details about the various builds packaged with Lyra.

The link: <https://github.com/LyraSearch/lyra#builds> is a dead end.

Thanks.

**Comment by micheleriva** [comment]
Hi! Would you mind opening a PR for this? :)

**Comment by djibe** [comment]
Hi. I thought to do so but I have no idea where the link should point to.

I'll do PR for my future Issues I can solve, promise !

**Comment by micheleriva** [comment]
Ahah alright then :)
