### ISSUE TITLE
Add ukrainian language

### ISSUE THREAD

**Issue by lpite** [LyraSearch/lyra#251]
**Is your feature request related to a problem? Please describe.**
Lyra can't search ukrainian letters such as Ї, ї, І, і, Є, є

**Describe the solution you'd like**
Add regex for ukrainian langugage
ukrainian: /[^a-z0-9а-яА-ЯіїєЇІЄ]+/gim

I can create pull request

**Comment by micheleriva** [comment]
Hi @lpite!
We would love a PR for this one. Thanks!

**Comment by ilteoood** [comment]
This has been closed with #252
