### ISSUE TITLE
Latin Extended character set is not covered in `tokenizer/diacritics`

### ISSUE THREAD

**Issue by bogacg** [LyraSearch/lyra#274]
While doing some tests originating from another inconvenience discussed in #273 I see that characters from ISO Latin Extended list are not covered in source file `tokenizer/diacritics.ts`

I did some research and [Oracle provides a good table](https://docs.oracle.com/cd/E29584_01/webhelp/mdex_basicDev/src/rbdv_chars_mapping.html) of these characters with their decimal codes.

I think I can send a PR using that table to fix the issue.

**Comment by micheleriva** [comment]
Thank you so much for the PR. Looks fantastic to me

**Comment by micheleriva** [comment]
Released in v0.4.6

**Comment by bogacg** [comment]
@micheleriva sorry for missing tests, I'll be more through next time.
