### ISSUE TITLE
Add support for Slovenian language

### ISSUE THREAD

**Issue by aldingithub** [LyraSearch/lyra#281]
**Is your feature request related to a problem? Please describe.**
As shown on the image below, search does not work correctly for some Slovenian words.
![res](https://user-images.githubusercontent.com/61204903/218046354-9eb54dd8-c895-4127-ad18-e119748569e2.png)

**Describe the solution you'd like**
Add support for Slovenian language with regex **/[^a-z0-9čžšČŽŠ]+/gim**

**Comment by aldingithub** [comment]
I have cloned your project and on separated branch **slovenian_language** added support for Slovenian language with specified regex. Also I have written some test, as presented below.

```js
  t.test("should not throw if if the language is supported", async t => {
    t.plan(1);

    try {
      await create({
        schema: {},
        defaultLanguage: "slovenian",
      });

      t.pass();
    } catch (e) {
      t.fail();
    }
  });
```
```js
t.test("should correctly search accented words in Slovenian", async t => {
  const db = await create({
    schema: {
      description: "string",
    },
    defaultLanguage: "slovenian",
  });

  await insert(db, {
    description: "ščisti se pešec čez križišče",
  });

  const searchResult = await search(db, {
    term: "križišče",
  });
  t.equal(searchResult.count, 1);
});
```

**Comment by micheleriva** [comment]
Hi @aldingithub, thank you! Would you mind opening a PR for this?

**Comment by aldingithub** [comment]
Sure, no problem.
