### ISSUE TITLE
Cannot find module **'src/types/index.js**

### ISSUE THREAD

**Issue by aldingithub** [LyraSearch/lyra#284]
**Describe the bug**
In new release 0.4.7
```
Error: node_modules/@lyrasearch/lyra/dist/types/facets.d.ts:1:48 - error TS2307: Cannot find module 'src/types' or its corresponding type declarations.

1 import { PropertiesSchema, PropertyType } from "src/types";
                                                 ~~~~~~~~~~~


Error: node_modules/@lyrasearch/lyra/dist/types/filters.d.ts:1:39 - error TS2307: Cannot find module 'src/types/index.js' or its corresponding type declarations.

1 import type { PropertiesSchema } from "src/types/index.js";
```

**To Reproduce**
1. npm install
2. npm start

**Additional context**
I fix the proposed error with replacing:
```import { PropertiesSchema, PropertyType } from "src/types";``` to
```import { PropertiesSchema, PropertyType } from "@lyrasearch/lyra/dist/types";``` in **node_modules/@lyrasearch/lyra/dist/types/facets.d.ts**
and
```import { PropertiesSchema } from "src/types";``` to
```import { PropertiesSchema } from "@lyrasearch/lyra/dist/types";```  in **node_modules/@lyrasearch/lyra/dist/types/filters.d.ts**

**Comment by micheleriva** [comment]
Hi!
I'm fixing this right now. ETA: 30min.
