### ISSUE TITLE
Benchmarks for typo tolerance do not perform typo-tolerant search

### ISSUE THREAD

**Issue by lucaong** [LyraSearch/lyra#49]
**Describe the bug**

The benchmarks for typo-tolerance are executing a search with `exact: true`, so they only perform exact match.

**To Reproduce**

No reproduction as this is a problem with the benchmarks, but see how [the benchmark sets `exact: true`](https://github.com/nearform/lyra/blob/d9b041e1195361ce9ae93b2c9efc76c1d6918bf3/packages/benchmarks/engines/typo-tolerance.js#L21). The current implementation (as of `Lyra 0.0.1-beta-14`) [returns early if `exact` is `true` and an exact match is found](https://github.com/nearform/lyra/blob/d9b041e1195361ce9ae93b2c9efc76c1d6918bf3/packages/lyra/src/prefix-tree/trie.ts#L73), no matter if `tolerance` is set.

**Expected behavior**

The benchmark for typo tolerance should perform a typo tolerant search.

**Note:** it would probably also make sense to disable stemming on the typo tolerance benchmarks to avoid confounding results.

**Comment by micheleriva** [comment]
We removed the benchmarks from this repo, as we'll create a separate one. Closing this for now
